### ISSUE TITLE
Unity Field only uses Mag as a negative number.

### ISSUE THREAD

**Issue by Ezmr7** [Pannoniae/BreakEternity.cs#1]
Using a Big Number as a SerializedField inputs only negative numbers when run. The only field is Mag and if I input 10, it comes out as -10 when the code is run. I assume this is an issue with sign not being a field and defaulting to negative, but I'm new to this library so I can't really say for sure.

**Comment by Pannoniae** [comment]
Don't manually change the fields, that's not a good idea. Use the constructors:)
